### ISSUE TITLE
Firefox sluggish, and about-addons-memory does not help identify the culprit

### ISSUE THREAD

**Issue by wildetudor** [nmaier/about-addons-memory#25]
Hello, I just installed about:addons-memory 2016 on Firefox 45.0.1 (running on Win 7), in the hopes of finding out why my Firefox becomes sluggish so quickly, while other programs on this PC run very fast. 

Under Task Manager, Firefox normally takes between around 500, sometimes up to 1000 MB, rarely more; even so (or maybe: because of this), script-intensive pages such Google Maps are invariably very slow to rspond, and even in simple pages Firefox is not as responsive (e.g. to Ctrl+F commands) as it should. 

The addon results (see below) are not very helpful, as I know it is normal for ABP to take up as much memory as it does. 

Can anyone help? Many thanks!
![18 04 2016 15 47 48](https://cloud.githubusercontent.com/assets/15835348/14606390/4c85e38a-057d-11e6-83a5-d6ca89808377.jpg)

**Comment by yfdyh000** [comment]
https://support.mozilla.org/kb/firefox-slow-how-make-it-faster

**Comment by wildetudor** [comment]
Thanks but those general tips did not help in my case - this is why I installed this add-on in the first place... Some help with my questions above would be appreciated.

**Comment by yfdyh000** [comment]
Use the about:memory to inspect if you think that it is a memory problem.
https://developer.mozilla.org/en-US/docs/Mozilla/Performance/about:memory

**Comment by wildetudor** [comment]
I suspect one of my add-ons is responsible for the memory-hog Firefox has become. Isn't the add-on we are talking about on this page (about-addons-memory) the one to use to identify the cluprit? The output of about:memory seems difficult to make sense of..

**Comment by rayman89** [comment]
Most of the time there is no simple way of determining what add-on caused it unless you have just installed some add-ons and it happened. Best solution to be sure is to disable all and try to reproduce the issue enabling them 1 by one but if you have many you might be screwed. 

 Things that helped me before is to remake my profile (aka creating a new profile and configuring all again and passing only the bookmarks and passwords) because the profile sometimes gets corrupted but lately this doesn't seem to happen but you can try if you have an old profile.

BTW1 If you are using over 200 tabs with heavy js/flash content  (memory usage near 2gb) then firefox is not able to handle it no matter how good your pc is and ti will have brief hangs I sent a bug report about this but they are not sure how to approach it or if they even going to sadly.

 BTW adblock was causing huge uses of memory they were supposed to fix it but idk if they did. If they did not I recommend to use ublock origin might look hard to use at first but is not that hard if you have this in mind: You can access the options pressing the button and then the small cog in the top left corner. The dropper from the menu allows you to select what to hide and the table next to it (once you press the refresh button on the new tab that opens) will show you all the elements scripts etc and tell you what is blocked and which list blocks it. Also

To exclude stuff on my filters
@@domain

To allow cosmetic filters for example if I want the ##.social_icons filter and the ###social_container to be disabled

#@#.social_icons
#@##social_container

For only a specific site:

example.com#@#.social_icons
example.com#@##social_container

To block stuff with random numbers on it
EX:
www.newgrounds.com###outer > .PalevioletredHighlevelRockrat1455516819
www.newgrounds.com###\38 38693 > div > a[href^="http://www.mmo123.co/egame"]

SOLUTION:
Some > can be omitted.
.name and #name can be written as [class="name"] and [id="name"].

EX:
newgrounds.com##div[class^=PalevioletredHighlevelRockrat]
newgrounds.com##a[href^="http://www.mmo123.co/egame"]
